server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true


    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowed-origins: "*"
                allowed-methods:
                - GET
                - POST
                - PUT
                - DELETE
                - PATCH
                allowed-headers:
                - "*"
                exposed-headers:
                - "*"

#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path=/products/**

#eureka:
#  client:
#    enabled: true
#  instance:
#    preferIpAddress=true: